[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m uvicorn main_node:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
ENVIRONMENT = "production"